export const TRANSACTION_MESSAGE = 'TRANSACTION_MESSAGE';
export const TRANSACTION_AMOUNT = 'TRANSACTION_AMOUNT';
export const TRANSACTION_EMAIL = 'TRANSACTION_EMAIL';
export const TRANSACTION_CHECK = 'TRANSACTION_CHECK';
export const SET_LOGO = 'SET_LOGO';
